name: Step 3, Copilot Hub Suggestion

# Trigger after push to main branch for member.js file.
on:
  workflow_dispatch:
  push:
    paths:
      - "member.js"
    branches:
      - main

permissions:
  contents: write

jobs:
  get_current_step:
    name: Check Current Step Number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - id: get_step
        run: echo "current_step=$(cat ./.github/steps/step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_Copilothub_suggestions:
    name: On Copilot Hub Suggestion
    needs: get_current_step
    if: ${{ !github.event.repository.is_template && needs.get_current_step.outputs.current_step == 3 }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Package for axios version 0.21.2
        uses: actions/action-check-file@v1
        with:
          file: "member.js"
          search: "skillsMember"

      - name: Update to Step 4
        uses: actions/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 3
          to_step: 4
